### ISSUE TITLE
Update DNS when behind NAT

### ISSUE THREAD

**Issue by fts-tmassey** [rrauenza/ez-ipupdate#1]
Hello!

I have created a script and configuration to allow ez-ipupdate to update a dynamic DNS entry when it is behind a NAT router.  I created this for Oracle Cloud VM's, which are assigned a private IP and uses 1:1 NAT to provide a public IP -- and obviously I can't run ez-ipupdate on their firewall...  :)

You can find the script here:  https://github.com/fts-tmassey/ez-ipupdate-nat

There's nothing too magical there, but it might save you a bit of time pulling it all together.  I hope it helps.

**Comment by fts-tmassey** [comment]
Closing issue

**Comment by rrauenza** [comment]
This is just a copy of the original...   I think just to get it to compile once with some local changes.  I'm not sure why I didn't even fork the original -- maybe it wasn't in github?

I think the original is source forge... https://sourceforge.net/projects/ez-ipupdate/

**Comment by MiM-TMassey** [comment]
That SourceForge page does seem like it might be the project home. But there hasn’t been an update in over five years… There was supposed to be a webpage for the project, but the DNS doesn’t resolve to anything.

So, it looks like my code is now the most recently updated… :-) Obviously there isn’t a rush of people adding new features. But at the least this might give a little more visibility to someone if they’re looking for the feature I added.

Thanks for the reply.

**Comment by fts-tmassey** [comment]
That SourceForge page does seem like it might be the project home. But there hasn’t been an update in over five years… There was supposed to be a webpage for the project, but the DNS doesn’t resolve to anything.

So, it looks like my code is now the most recently updated… :-) Obviously there isn’t a rush of people adding new features. But at the least this might give a little more visibility to someone if they’re looking for the feature I added.

Thanks for the reply.
